FP16 Java support
openjdk/panama-vector pull request #164
Opened 2021-11-16 23:52 UTC by smita-kamath

Initial FP16 vectorAPI Java support.

2022-02-10 02:30 UTC, jatin-bhateja commented
Hi Smita,
Following patch fixes the failing base testcase.
Thanks,
Jatin

```
diff --git a/src/jdk.incubator.vector/share/classes/jdk/incubator/vector/AbstractSpecies.java b/src/jdk.incubator.vector/share/classes/jdk/incubator/vector/AbstractSpecies.java
index 18c0cb9a725..9def1acdd61 100644
--- a/src/jdk.incubator.vector/share/classes/jdk/incubator/vector/AbstractSpecies.java
+++ b/src/jdk.incubator.vector/share/classes/jdk/incubator/vector/AbstractSpecies.java
@@ -298,7 +298,16 @@ abstract class AbstractSpecies<E> extends jdk.internal.vm.vector.VectorSupport.V
         return makeDummyVector();
     }
     private AbstractVector<E> makeDummyVector() {
-        Object za = Array.newInstance(elementType(), laneCount);
+        Object za;
+        // FIXME: Remove following special handling for Halffloat
+        // till Valhalla integration when Halffloat will become a
+        // primitive class.
+        if (elementType() == Halffloat.class)  {
+           za = Array.newInstance(short.class, laneCount);
+        } else {
+           za = Array.newInstance(elementType(), laneCount);
+        }
+
         return dummyVector = vectorFactory.apply(za);
         // This is the only use of vectorFactory.
         // All other factory requests are routed
diff --git a/test/jdk/jdk/incubator/vector/AddTest.java b/test/jdk/jdk/incubator/vector/AddTest.java
index 7c6329a7a3c..7ce077f75ec 100644
--- a/test/jdk/jdk/incubator/vector/AddTest.java
+++ b/test/jdk/jdk/incubator/vector/AddTest.java
@@ -44,20 +44,18 @@ public class AddTest {
     static short[] a = new short[SIZE];
     static short[] b = new short[SIZE];
     static short[] c = new short[SIZE];
-
     static {
         for (int i = 0; i < SIZE; i++) {
-            a[i] = 0x3C66;
-            b[i] = 0x4066;
+            a[i] = Halffloat.valueOf((float)i);
+            b[i] = Halffloat.valueOf((float)i);
         }
     }
 
     static void workload() {
         for (int i = 0; i < a.length; i += SPECIES.length()) {
             HalffloatVector av = HalffloatVector.fromArray(SPECIES, a, i);
-            //HalffloatVector bv = HalffloatVector.fromArray(SPECIES, b, i);
-            //av.add(bv).intoArray(c, i);
-            av.intoArray(c,i);
+            HalffloatVector bv = HalffloatVector.fromArray(SPECIES, b, i);
+            av.add(bv).intoArray(c, i);
         }
     }
 
@@ -76,8 +74,14 @@ public class AddTest {
             workload();
         }
         for (int i = 0; i < a.length; i++) {
-            if (c[i] != a[i] + b[i])
+            Halffloat hfa = new Halffloat(a[i]);
+            Halffloat hfb = new Halffloat(b[i]);
+            Halffloat hfc = new Halffloat(c[i]);
+
+            if (hfc.floatValue() != (hfa.floatValue() + hfb.floatValue())) {
+                System.out.println("RES: " + hfc.floatValue() + " EXPECTED: " + (hfa.floatValue() + hfb.floatValue()));
                 throw new AssertionError();
+            }
         }
 
         /*Arrays.fill(c, 0.0f);
@@ -89,5 +93,6 @@ public class AddTest {
             if (c[i] != a[i] + b[i])
                 throw new AssertionError();
         }*/
+        System.out.println("PASSED");
     }
 }

```

2022-06-13 18:04 UTC, jatin-bhateja commented on src/jdk.incubator.vector/share/classes/jdk/incubator/vector/FloatVector.java
> +                                wb_.putFloat(o + i * 4, e));
Same as above, kindly

2022-06-15 14:56 UTC, jatin-bhateja commented on src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Halffloat.java
> +    }
Please add a switch to handle special case values (NaN, Inf, -Inf),  i.e. HF.NaN -> Float.NaN :

2022-06-15 14:57 UTC, jatin-bhateja commented on src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Halffloat.java
> +        return Math.abs(f) <= Halffloat.MAX_VALUE;
We are comparing abs value with short. wont work well.

2022-06-15 18:04 UTC, jatin-bhateja commented on src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Halffloat.java
> +     public Halffloat(short value) {
It will be useful if we can have a constructor accepting float also.

2022-06-15 18:05 UTC, jatin-bhateja commented on src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Halffloat.java
> +        if (!Float.isFinite(f)) return Halffloat.POSITIVE_INFINITY;
Will be appropriate if range bound checks are done against Halffloat bounds.

2022-06-16 01:53 UTC, jatin-bhateja commented on src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Halffloat.java
> +        val = ((((val>>16)&0x8000)|((((val&0x7f800000)-0x38000000)>>13)&0x7c00)|((val>>13)&0x03ff)));
Kindly also add the link to paper.

2022-06-16 01:54 UTC, jatin-bhateja commented
Initial version looks ok to me, we can do refinement in subsequent patches.

2022-06-16 05:28 UTC, smita-kamath commented
Reference to Fast float to halffloat conversion: http://fox-toolkit.org/ftp/fasthalffloatconversion.pdf

2022-06-16 07:19 UTC, jatin-bhateja requested changes
Failures seen during jtreg, needs fix.

2022-06-22 22:52 UTC, sviswa7 approved these changes
Looks good to me.

2022-06-22 22:54 UTC, smita-kamath commented
/integrate

2022-06-22 23:19 UTC, sviswa7 commented
/sponsor

2022-06-22 23:20 UTC, closed without merging